[package]
name = "op-angstrom"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = """
Angstrom Sidecar implementation
"""

[dependencies]
angstrom-cli.workspace = true

[target.'cfg(unix)'.dependencies]
tikv-jemallocator = { version = "0.6.0", optional = true }

[features]
default = ["jemalloc"]
jemalloc = ["dep:tikv-jemallocator"]
jemalloc-prof = ["jemalloc", "tikv-jemallocator?/profiling"]

[[bin]]
name = "op-angstrom"
path = "src/main.rs"

[dev-dependencies]
alloy.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types.workspace = true
angstrom-rpc.workspace = true
angstrom-types.workspace = true
eyre.workspace = true
futures.workspace = true
jsonrpsee.workspace = true
pade.workspace = true
reth.workspace = true
reth-provider = { workspace = true, features = ["test-utils"] }
reth-tasks.workspace = true
serial_test.workspace = true
testing-tools.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
